# Generated by Django 4.0.2 on 2022-03-02 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назвние категории:')),
                ('url', models.SlugField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя польщователя')),
                ('Email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-username'],
            },
        ),
        migrations.CreateModel(
            name='Tato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Имя клиента:')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Изображение:')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки:')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмтры:')),
                ('description', models.TextField(null=True, verbose_name='Описание:')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.category')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.comment')),
            ],
        ),
        migrations.CreateModel(
            name='TatoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера:')),
                ('skill', models.CharField(max_length=500, verbose_name='Стаж работы:')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Фото мастр:')),
                ('about_us', models.TextField(verbose_name='О себе:')),
                ('kay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.tato')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
