# Generated by Django 4.0.1 on 2022-03-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя пользователяц:'),
        ),
        migrations.AlterField(
            model_name='tatomaster',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Фото мастера:'),
        ),
    ]
