# Generated by Django 4.0.1 on 2022-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_comment_username_alter_tatomaster_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tato',
            options={'verbose_name': 'Тату', 'verbose_name_plural': 'Татуировки'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=123, verbose_name='Описание:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tato',
            name='url',
            field=models.SlugField(default=2312, max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tato',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение:'),
        ),
    ]
