# Generated by Django 4.0.1 on 2022-03-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_tato_options_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tato',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
