# Generated by Django 4.0.1 on 2022-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_remove_tato_url_alter_tato_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tatomaster',
            old_name='kay',
            new_name='tatos',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tato',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tato',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Изображение:'),
        ),
        migrations.AlterField(
            model_name='tato',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена:'),
        ),
    ]
